// SPDX-License-Identifier: MIT
/**
 * Writes `src/generated/messages.ts` (message keys, their placeholders, plural families) from `src/locales/en.json`
 * and the English feature catalogues (`src/locales/<feature>.en.json`), so a call with an unknown key or a wrong
 * placeholder name does not compile.
 *
 * Feature catalogues hold keys that only some pages use (`FEATURES`). They are loaded on demand by those pages
 * (`loadFeature`, `featureTranslator`), so the catalogue every page carries, the pay route's first load included
 * (PAYLINK-V2-SPEC §4.4: 110 kB of gzipped JavaScript), does not grow with them. The list is closed: a new feature
 * catalogue is a reviewed change.
 *
 * Usage (from packages/i18n):  node scripts/generate.ts          write the file
 *                              node scripts/generate.ts --check  exit 1 if the file is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE = resolve(PACKAGE_DIR, "src/locales/en.json");
export const OUTPUT = resolve(PACKAGE_DIR, "src/generated/messages.ts");
/** Feature catalogues; each key of feature `f` starts with `f.` and lives in `src/locales/f.<locale>.json`. */
export const FEATURES = ["books"] as const;
export const featureSource = (feature: string, locale = "en"): string => resolve(PACKAGE_DIR, `src/locales/${feature}.${locale}.json`);

const PLURAL_CATEGORIES = ["zero", "one", "two", "few", "many", "other"] as const;
const PLACEHOLDER = /\{([A-Za-z][A-Za-z0-9]*)\}/g;

const names = (message: string): string[] => [...new Set([...message.matchAll(PLACEHOLDER)].map((m) => m[1] ?? ""))].sort();
/** `never` marks a message without placeholders (`ParamsOf` maps it to an empty parameter object). */
const params = (list: readonly string[]): string => (list.length === 0 ? "never" : `{ ${list.map((n) => `readonly ${n}: ParamValue`).join("; ")} }`);

/** The plural family a key belongs to (`ledger.payments.one` → `ledger.payments`), when its `.other` exists. */
export function pluralBase(key: string, keys: ReadonlySet<string>): string | null {
  const dot = key.lastIndexOf(".");
  const base = key.slice(0, dot);
  const category = key.slice(dot + 1);
  return (PLURAL_CATEGORIES as readonly string[]).includes(category) && keys.has(`${base}.other`) ? base : null;
}

/**
 * The generated module for the merged English messages (`messages`: the core catalogue, then each feature's) and the
 * keys of each feature catalogue (`features`).
 */
export function render(messages: Readonly<Record<string, string>>, features: Readonly<Record<string, readonly string[]>> = {}): string {
  const keys = Object.keys(messages);
  const keySet = new Set(keys);
  const families = new Map<string, Set<string>>();
  for (const key of keys) {
    const base = pluralBase(key, keySet);
    if (base !== null) {
      const set = families.get(base) ?? new Set(["count"]);
      for (const n of names(messages[key] ?? "")) {
        set.add(n);
      }
      families.set(base, set);
    }
  }
  const lines = [
    "// SPDX-License-Identifier: MIT",
    "// Generated by packages/i18n/scripts/generate.ts from src/locales/en.json and the feature catalogues",
    "// (src/locales/<feature>.en.json). Do not edit by hand: run `pnpm --filter @paylink/i18n run generate` after changing them.",
    "",
    'import type { ParamValue } from "../interpolate.ts";',
    "",
    "/** Every message key (en.json is the reference catalogue). */",
    `export type MessageKey =\n${keys.map((k) => `  | ${JSON.stringify(k)}`).join("\n")};`,
    "",
    "/** The named placeholders of each message; `never` when it has none. */",
    "export interface MessageParams {",
    ...keys.map((k) => `  readonly ${JSON.stringify(k)}: ${params(names(messages[k] ?? ""))};`),
    "}",
    "",
    "/** Plural families: `<base>.one`, `<base>.other`, … selected with Intl.PluralRules. */",
    `export type PluralBase =${families.size === 0 ? " never" : `\n${[...families.keys()].map((k) => `  | ${JSON.stringify(k)}`).join("\n")}`};`,
    "",
    "/** The placeholders of a plural family (the union over its variants, `count` included). */",
    "export interface PluralParams {",
    ...[...families].map(([base, set]) => `  readonly ${JSON.stringify(base)}: ${params([...set].sort())};`),
    "}",
    "",
    "/** Feature catalogues, loaded on demand by the pages that use them (`loadFeature`). */",
    `export type Feature =${Object.keys(features).length === 0 ? " never" : `\n${Object.keys(features).map((f) => `  | ${JSON.stringify(f)}`).join("\n")}`};`,
    "",
    "/** Keys that live in a feature catalogue, not in the catalogue every page carries. */",
    `export type FeatureKey =${Object.values(features).flat().length === 0 ? " never" : `\n${Object.values(features).flat().map((k) => `  | ${JSON.stringify(k)}`).join("\n")}`};`,
    "",
  ];
  return lines.join("\n");
}

/** The English core catalogue merged with each feature's, and the keys of each feature. Refuses a misplaced key. */
export function sources(): { readonly messages: Record<string, string>; readonly features: Record<string, string[]> } {
  const messages = JSON.parse(readFileSync(SOURCE, "utf8")) as Record<string, string>;
  const features: Record<string, string[]> = {};
  for (const feature of FEATURES) {
    const own = JSON.parse(readFileSync(featureSource(feature), "utf8")) as Record<string, string>;
    for (const key of Object.keys(own)) {
      if (!key.startsWith(`${feature}.`) || Object.hasOwn(messages, key)) {
        throw new Error(`${feature}.en.json: ${key} is not a ${feature} key, or is also in en.json`);
      }
      messages[key] = own[key] ?? "";
    }
    features[feature] = Object.keys(own);
  }
  return { messages, features };
}

function main(argv: readonly string[]): number {
  const { messages, features } = sources();
  const content = render(messages, features);
  let current: string;
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    current = "";
  }
  if (current === content) {
    return 0;
  }
  if (argv.includes("--check")) {
    console.error("stale: src/generated/messages.ts (run: pnpm --filter @paylink/i18n run generate)");
    return 1;
  }
  writeFileSync(OUTPUT, content);
  console.log("wrote src/generated/messages.ts");
  return 0;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
