// SPDX-License-Identifier: MIT
/**
 * Writes `src/generated/messages.ts` (message keys, their placeholders, plural families) from `src/locales/en.json`,
 * so a call with an unknown key or a wrong placeholder name does not compile.
 *
 * Usage (from packages/i18n):  node scripts/generate.ts          write the file
 *                              node scripts/generate.ts --check  exit 1 if the file is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE = resolve(PACKAGE_DIR, "src/locales/en.json");
export const OUTPUT = resolve(PACKAGE_DIR, "src/generated/messages.ts");

const PLURAL_CATEGORIES = ["zero", "one", "two", "few", "many", "other"] as const;
const PLACEHOLDER = /\{([A-Za-z][A-Za-z0-9]*)\}/g;

const names = (message: string): string[] => [...new Set([...message.matchAll(PLACEHOLDER)].map((m) => m[1] ?? ""))].sort();
/** `never` marks a message without placeholders (`ParamsOf` maps it to an empty parameter object). */
const params = (list: readonly string[]): string => (list.length === 0 ? "never" : `{ ${list.map((n) => `readonly ${n}: ParamValue`).join("; ")} }`);

/** The plural family a key belongs to (`ledger.payments.one` → `ledger.payments`), when its `.other` exists. */
export function pluralBase(key: string, keys: ReadonlySet<string>): string | null {
  const dot = key.lastIndexOf(".");
  const base = key.slice(0, dot);
  const category = key.slice(dot + 1);
  return (PLURAL_CATEGORIES as readonly string[]).includes(category) && keys.has(`${base}.other`) ? base : null;
}

export function render(messages: Readonly<Record<string, string>>): string {
  const keys = Object.keys(messages);
  const keySet = new Set(keys);
  const families = new Map<string, Set<string>>();
  for (const key of keys) {
    const base = pluralBase(key, keySet);
    if (base !== null) {
      const set = families.get(base) ?? new Set(["count"]);
      for (const n of names(messages[key] ?? "")) {
        set.add(n);
      }
      families.set(base, set);
    }
  }
  const lines = [
    "// SPDX-License-Identifier: MIT",
    "// Generated by packages/i18n/scripts/generate.ts from src/locales/en.json. Do not edit by hand:",
    "// run `pnpm --filter @paylink/i18n run generate` after changing en.json.",
    "",
    'import type { ParamValue } from "../interpolate.ts";',
    "",
    "/** Every message key (en.json is the reference catalogue). */",
    `export type MessageKey =\n${keys.map((k) => `  | ${JSON.stringify(k)}`).join("\n")};`,
    "",
    "/** The named placeholders of each message; `never` when it has none. */",
    "export interface MessageParams {",
    ...keys.map((k) => `  readonly ${JSON.stringify(k)}: ${params(names(messages[k] ?? ""))};`),
    "}",
    "",
    "/** Plural families: `<base>.one`, `<base>.other`, … selected with Intl.PluralRules. */",
    `export type PluralBase =${families.size === 0 ? " never" : `\n${[...families.keys()].map((k) => `  | ${JSON.stringify(k)}`).join("\n")}`};`,
    "",
    "/** The placeholders of a plural family (the union over its variants, `count` included). */",
    "export interface PluralParams {",
    ...[...families].map(([base, set]) => `  readonly ${JSON.stringify(base)}: ${params([...set].sort())};`),
    "}",
    "",
  ];
  return lines.join("\n");
}

function main(argv: readonly string[]): number {
  const messages = JSON.parse(readFileSync(SOURCE, "utf8")) as Record<string, string>;
  const content = render(messages);
  let current: string;
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    current = "";
  }
  if (current === content) {
    return 0;
  }
  if (argv.includes("--check")) {
    console.error("stale: src/generated/messages.ts (run: pnpm --filter @paylink/i18n run generate)");
    return 1;
  }
  writeFileSync(OUTPUT, content);
  console.log("wrote src/generated/messages.ts");
  return 0;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
