// SPDX-License-Identifier: MIT
/**
 * Writes `src/generated/paylink-v2-abi.ts` from the Foundry artifact of the release build
 * (`protocol/out/PayLinkV2.sol/PayLinkV2.json`, produced by `forge build` in protocol/).
 *
 * Usage (from packages/sdk):  node scripts/generate-abi.ts          write the file
 *                             node scripts/generate-abi.ts --check  exit 1 if the file is stale
 *
 * The committed file does not depend on a local build: test/abi.test.ts checks every selector against the
 * literal tables of the invoice spec (§7.6, §17.2) on every run, and compares the whole ABI with the
 * artifact whenever `protocol/out` exists (CI's contracts job, or after `forge build`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const ARTIFACT = resolve(PACKAGE_DIR, "../../protocol/out/PayLinkV2.sol/PayLinkV2.json");
export const OUTPUT = resolve(PACKAGE_DIR, "src/generated/paylink-v2-abi.ts");

/** Renders the TypeScript module for an ABI (a JSON array as Foundry writes it). */
export function renderAbi(abi: readonly unknown[]): string {
  const body = JSON.stringify(abi, null, 2);
  return `// SPDX-License-Identifier: MIT
// Generated by packages/sdk/scripts/generate-abi.ts from protocol/out/PayLinkV2.sol/PayLinkV2.json
// (release build: solc 0.8.30, paris, OpenZeppelin 5.3.0). Do not edit by hand:
// run \`pnpm --filter @paylink/sdk run generate\` after \`forge build\` in protocol/.

/** ABI of PayLinkV2, including the OpenZeppelin errors and events it inherits. */
export const payLinkV2Abi = ${body} as const;
`;
}

export function readArtifactAbi(path: string = ARTIFACT): readonly unknown[] {
  const artifact = JSON.parse(readFileSync(path, "utf8")) as { abi?: unknown };
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`${path}: no abi array`);
  }
  return artifact.abi as readonly unknown[];
}

function main(argv: readonly string[]): number {
  const content = renderAbi(readArtifactAbi());
  let current: string;
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    current = "";
  }
  if (current === content) {
    return 0;
  }
  if (argv.includes("--check")) {
    console.error("stale: src/generated/paylink-v2-abi.ts (run: node scripts/generate-abi.ts)");
    return 1;
  }
  writeFileSync(OUTPUT, content);
  console.log("wrote src/generated/paylink-v2-abi.ts");
  return 0;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
