// SPDX-License-Identifier: MIT
/**
 * Generates `src/generated/*.ts` from the protocol's machine-written records, so that the registry
 * never restates a number or an address by hand:
 *
 * | Output                        | Source                                         |
 * |-------------------------------|------------------------------------------------|
 * | src/generated/gas.ts          | protocol/snapshots/PayLinkV2.json (forge gas)  |
 * |                               | and data/gas-measurements.json (anvil, per net)|
 * | src/generated/release.ts      | protocol/deployments/release.json              |
 * | src/generated/deployments.ts  | protocol/deployments/<chainId>.json            |
 * | src/generated/v1.ts           | web/config.js (frozen v1 app, Arc mainnet)     |
 *
 * Usage (from packages/chains):  node scripts/generate.ts          write the files
 *                                node scripts/generate.ts --check  exit 1 if any file is stale
 *
 * `test/generated.test.ts` runs the same renderers and fails CI when a committed file is stale.
 * The script runs on Node's built-in type stripping (Node >= 22.18), so it imports nothing from `src/`
 * except types.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getAddress, isHex } from "viem";
import type { PayLinkFunction } from "../src/types.ts";

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPO_DIR = resolve(PACKAGE_DIR, "../..");

export const SOURCES = {
  gasSnapshot: "protocol/snapshots/PayLinkV2.json",
  gasMeasurements: "packages/chains/data/gas-measurements.json",
  release: "protocol/deployments/release.json",
  deploymentsDir: "protocol/deployments",
  v1Config: "web/config.js",
} as const;

const HEADER = (source: string): string =>
  `// SPDX-License-Identifier: MIT\n// Generated by packages/chains/scripts/generate.ts from ${source}. Do not edit by hand:\n// run \`pnpm --filter @paylink/chains run generate\` after the source changes.\n`;

// ------------------------------------------------------------------------------------------- gas

/** The six state-changing entry points, in ABI order of the spec's interface (§3.3.2). */
export const GAS_FUNCTIONS: readonly PayLinkFunction[] = [
  "payWithAuthorization",
  "pay",
  "payWithPermit",
  "payNative",
  "cancel",
  "cancelBySig",
];

/** Snapshot entries kept for reference but not turned into limits. */
const INFORMATIONAL = new Set(["deploy", "statesOf"]);
/** Variants measured with an EOA payee: they set the floor. */
const EOA_VARIANTS = new Set(["", "first", "repeat"]);
/** Variant measured with an ERC-1271 payee: it must fit under the ceiling (spec §3.3.6). */
const CONTRACT_PAYEE_VARIANT = "erc1271Payee";

/** Margin that clients add to `eth_estimateGas` (spec §3.3.6: × 1.10), as a fraction. */
export const ESTIMATE_MARGIN = { numerator: 110n, denominator: 100n } as const;
/** Ceiling = 1.5 × floor (spec §3.3.6), as a fraction. */
export const CEILING_FACTOR = { numerator: 3n, denominator: 2n } as const;
/** Limits are rounded up to this granularity. */
export const ROUNDING = 1000n;

const ceilDiv = (a: bigint, b: bigint): bigint => (a + b - 1n) / b;
const roundUp = (value: bigint): bigint => ceilDiv(value, ROUNDING) * ROUNDING;

export interface DerivedGas {
  readonly measurements: ReadonlyMap<string, bigint>;
  readonly limits: ReadonlyMap<PayLinkFunction, { floor: bigint; ceiling: bigint }>;
}

/**
 * Derives the per-function gas bounds from a Foundry gas snapshot (spec §3.3.6):
 * - floor = the largest EOA-payee measurement of the function (first and repeat payments), rounded up to 1,000;
 * - ceiling = 1.5 × floor, rounded up to 1,000;
 * - every ERC-1271-payee measurement, plus the 10 % estimate margin, must fit under the ceiling.
 * Unknown entries fail loudly, so a new snapshot entry is always mapped on purpose.
 */
export function deriveGasBounds(snapshot: Readonly<Record<string, unknown>>): DerivedGas {
  const measurements = new Map<string, bigint>();
  const eoa = new Map<PayLinkFunction, bigint>();
  const contractPayee = new Map<PayLinkFunction, bigint>();
  const functions = new Set<string>(GAS_FUNCTIONS);

  for (const name of Object.keys(snapshot).sort()) {
    const raw = snapshot[name];
    if (typeof raw !== "string" || !/^[1-9][0-9]{0,15}$/.test(raw)) {
      throw new Error(`gas snapshot: ${name} must be a positive decimal string, got ${JSON.stringify(raw)}`);
    }
    const gas = BigInt(raw);
    measurements.set(name, gas);
    const separator = name.indexOf("_");
    const fn = separator === -1 ? name : name.slice(0, separator);
    const variant = separator === -1 ? "" : name.slice(separator + 1);
    if (INFORMATIONAL.has(fn)) {
      continue;
    }
    if (!functions.has(fn)) {
      throw new Error(`gas snapshot: unknown entry ${name} (map it in scripts/generate.ts)`);
    }
    const key = fn as PayLinkFunction;
    if (EOA_VARIANTS.has(variant)) {
      const previous = eoa.get(key) ?? 0n;
      eoa.set(key, gas > previous ? gas : previous);
    } else if (variant === CONTRACT_PAYEE_VARIANT) {
      contractPayee.set(key, gas);
    } else {
      throw new Error(`gas snapshot: unknown variant ${name} (map it in scripts/generate.ts)`);
    }
  }

  const limits = new Map<PayLinkFunction, { floor: bigint; ceiling: bigint }>();
  for (const fn of GAS_FUNCTIONS) {
    const measured = eoa.get(fn);
    if (measured === undefined) {
      throw new Error(`gas snapshot: no EOA-payee measurement for ${fn}`);
    }
    const floor = roundUp(measured);
    const ceiling = roundUp(ceilDiv(floor * CEILING_FACTOR.numerator, CEILING_FACTOR.denominator));
    const worst = contractPayee.get(fn);
    if (worst !== undefined) {
      const needed = ceilDiv(worst * ESTIMATE_MARGIN.numerator, ESTIMATE_MARGIN.denominator);
      if (needed > ceiling) {
        throw new Error(`gas snapshot: ${fn} ERC-1271 payee needs ${needed} gas with the margin, above the ceiling ${ceiling}`);
      }
    }
    limits.set(fn, { floor, ceiling });
  }
  return { measurements, limits };
}

const gasLiteral = (value: bigint): string => `${value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, "_")}n`;

/** One scenario measured on an anvil node: the smallest working gas limit and the receipt's gas used. */
export interface Measurement {
  readonly estimate: number;
  readonly gasUsed: number;
}

export interface MeasuredProfile {
  readonly chainId: number;
  readonly hardfork: string;
  readonly network: string;
  readonly appliesTo: readonly number[];
  readonly measurements: Readonly<Record<string, Measurement>>;
}

export interface MeasurementsFile {
  readonly tool: string;
  readonly profiles: Readonly<Record<string, MeasuredProfile>>;
}

/**
 * Profiles whose gas schedule differs from Ethereum's, so that their own estimates define the bounds of the
 * chains they apply to. Monad: cold SLOAD 8,100, cold account 10,100, ecrecover 6,000, and the gas limit
 * is charged (spec §3.3.6). Every other profile must fit under the snapshot bounds.
 */
export const EMULATED_PROFILES: ReadonlySet<string> = new Set(["monad"]);

const positive = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value > 0;

/** Validates data/gas-measurements.json (written by packages/sdk/scripts/measure-gas.ts) against the release. */
export function parseMeasurements(text: string, initCodeHash: string): MeasurementsFile {
  const file = JSON.parse(text) as Record<string, unknown>;
  expect(file["schema"] === "paylink.gas-measurements/1", "gas measurements: schema must be paylink.gas-measurements/1");
  expect(file["initCodeHash"] === initCodeHash, "gas measurements: measured on another build than release.json (re-run measure-gas.ts)");
  expect(typeof file["tool"] === "string", "gas measurements: tool missing");
  const profiles = file["profiles"] as Record<string, Record<string, unknown>>;
  for (const [name, profile] of Object.entries(profiles)) {
    expect(positive(profile["chainId"]) && typeof profile["hardfork"] === "string" && typeof profile["network"] === "string", `gas measurements: profile ${name}`);
    const appliesTo = profile["appliesTo"];
    expect(Array.isArray(appliesTo) && appliesTo.every(positive), `gas measurements: profile ${name} appliesTo`);
    for (const [scenario, m] of Object.entries(profile["measurements"] as Record<string, Record<string, unknown>>)) {
      expect(positive(m["estimate"]) && positive(m["gasUsed"]), `gas measurements: ${name}.${scenario} needs positive estimate and gasUsed`);
    }
  }
  return { tool: file["tool"], profiles: profiles as unknown as Record<string, MeasuredProfile> };
}

/** Bounds derived from a profile's estimates, with the same rule as the snapshot. */
export function deriveEmulatedBounds(profile: MeasuredProfile): DerivedGas {
  return deriveGasBounds(Object.fromEntries(Object.entries(profile.measurements).map(([name, m]) => [name, String(m.estimate)])));
}

/**
 * Throws when a measured transaction could not be sent within `limits`: its estimate plus the 10 % margin
 * must fit under the ceiling of its function.
 */
export function checkCoverage(profileName: string, profile: MeasuredProfile, limits: ReadonlyMap<PayLinkFunction, { floor: bigint; ceiling: bigint }>): void {
  for (const [scenario, m] of Object.entries(profile.measurements)) {
    const fn = scenario.split("_")[0] as PayLinkFunction;
    const bounds = limits.get(fn);
    expect(bounds !== undefined, `gas measurements: ${profileName}.${scenario} has no function bounds`);
    const needed = ceilDiv(BigInt(m.estimate) * ESTIMATE_MARGIN.numerator, ESTIMATE_MARGIN.denominator);
    expect(needed <= bounds.ceiling, `gas measurements: ${profileName}.${scenario} needs ${needed} gas with the margin, above the ceiling ${bounds.ceiling}`);
  }
}

const renderBounds = (limits: ReadonlyMap<PayLinkFunction, { floor: bigint; ceiling: bigint }>, indent: string): string =>
  GAS_FUNCTIONS.map((fn) => {
    const b = limits.get(fn);
    if (b === undefined) {
      throw new Error(`unreachable: ${fn}`);
    }
    return `${indent}${fn}: { floor: ${gasLiteral(b.floor)}, ceiling: ${gasLiteral(b.ceiling)} },`;
  }).join("\n");

export function renderGas(snapshotText: string, measurementsText: string, initCodeHash: string): string {
  const snapshot = JSON.parse(snapshotText) as Record<string, unknown>;
  const { measurements, limits } = deriveGasBounds(snapshot);
  const measured = parseMeasurements(measurementsText, initCodeHash);
  const emulated: string[] = [];
  const profiles: string[] = [];
  for (const [name, profile] of Object.entries(measured.profiles).sort(([a], [b]) => a.localeCompare(b))) {
    if (EMULATED_PROFILES.has(name)) {
      const derived = deriveEmulatedBounds(profile);
      checkCoverage(name, profile, derived.limits);
      emulated.push(`  ${name}: {\n${renderBounds(derived.limits, "    ")}\n  },`);
    } else {
      checkCoverage(name, profile, limits);
    }
    const rows = Object.entries(profile.measurements)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([scenario, m]) => `      ${scenario}: { estimate: ${m.estimate}, gasUsed: ${m.gasUsed} },`)
      .join("\n");
    profiles.push(
      `  ${name}: {\n    chainId: ${profile.chainId},\n    hardfork: ${JSON.stringify(profile.hardfork)},\n    network: ${JSON.stringify(profile.network)},\n    appliesTo: [${profile.appliesTo.join(", ")}],\n    measurements: {\n${rows}\n    },\n  },`,
    );
  }
  const snapshotRows = [...measurements].map(([name, gas]) => `  ${name}: ${gasLiteral(gas)},`).join("\n");
  return `${HEADER(`${SOURCES.gasSnapshot} and ${SOURCES.gasMeasurements}`)}//
// Rule (PAYLINK-V2-SPEC §3.3.6): floor = the largest EOA-payee measurement of the function (first and repeat
// payments), ceiling = 1.5 x floor, both rounded up to the next 1,000 gas. Each ERC-1271-payee measurement plus
// the 10 % estimate margin fits under the ceiling.
// - Snapshot bounds: Foundry in-test gas with Ethereum prices against mock tokens (protocol/audit/gas.md). The
//   generator refuses them unless every eth_estimateGas measured on the Ethereum-priced anvil profiles (Ethereum,
//   Base, London for Mezo) plus 10 % fits under the ceiling.
// - Emulated bounds (Monad): the same rule applied to eth_estimateGas on anvil's Monad emulation (MonadTen),
//   because Monad prices cold state and ecrecover differently and charges the gas limit.
// Both are provisional until re-measured on each testnet with cold slots and the real tokens.
import type { GasBounds, PayLinkFunction } from "../types.ts";

/** Raw per-call gas measurements written by \`protocol/test/gas/Gas.t.sol\`. */
export const GAS_SNAPSHOT_MEASUREMENTS = {
${snapshotRows}
} as const;

/** Gas-limit bounds derived from the snapshot (Ethereum gas prices). */
export const SNAPSHOT_GAS_LIMITS: Readonly<Record<PayLinkFunction, GasBounds>> = {
${renderBounds(limits, "  ")}
};

/** eth_estimateGas and receipt gasUsed per scenario, on anvil nodes emulating each network (${measured.tool}). */
export const GAS_MEASUREMENTS = {
${profiles.join("\n")}
} as const;

/** Gas-limit bounds of the networks whose gas schedule differs from Ethereum's, from their own estimates. */
export const EMULATED_GAS_LIMITS = {
${emulated.join("\n")}
} as const satisfies Readonly<Record<string, Readonly<Record<PayLinkFunction, GasBounds>>>>;
`;
}

// --------------------------------------------------------------------------------------- release

const HEX32 = /^0x[0-9a-f]{64}$/;

function expect(condition: boolean, message: string): asserts condition {
  if (!condition) {
    throw new Error(message);
  }
}

function checksummed(value: unknown, field: string): `0x${string}` {
  expect(typeof value === "string" && /^0x[0-9a-fA-F]{40}$/.test(value), `${field}: not an address`);
  const address = getAddress(value);
  expect(address === value, `${field}: ${value} is not EIP-55 checksummed (expected ${address})`);
  return address;
}

function hash32(value: unknown, field: string): `0x${string}` {
  expect(typeof value === "string" && HEX32.test(value) && isHex(value), `${field}: not a lowercase bytes32`);
  return value;
}

interface ReleaseRecord {
  readonly release: string;
  readonly bytecode: {
    readonly initCodeHash: string;
    readonly initCodeSize: number;
    readonly maskedRuntimeHash: string;
    readonly runtimeCodeSize: number;
    readonly immutableReferences: readonly { readonly start: number; readonly length: number }[];
    readonly cborMetadata: string;
  };
  readonly compiler: { readonly solc: string; readonly evmVersion: string; readonly settingsHash: string };
  readonly dependencies: Readonly<Record<string, string>>;
  readonly create2: { readonly factory: string; readonly salt: string; readonly saltPreimage: string; readonly address: string };
}

export function parseRelease(text: string): ReleaseRecord {
  const r = JSON.parse(text) as Record<string, unknown> & ReleaseRecord;
  expect(r["schema"] === "paylink.release/1", "release.json: schema must be paylink.release/1");
  expect(r["contract"] === "PayLinkV2", "release.json: contract must be PayLinkV2");
  expect(typeof r.release === "string" && /^\d+\.\d+\.\d+$/.test(r.release), "release.json: release must be semver");
  hash32(r.bytecode.initCodeHash, "release.bytecode.initCodeHash");
  hash32(r.bytecode.maskedRuntimeHash, "release.bytecode.maskedRuntimeHash");
  hash32(r.compiler.settingsHash, "release.compiler.settingsHash");
  hash32(r.create2.salt, "release.create2.salt");
  checksummed(r.create2.factory, "release.create2.factory");
  checksummed(r.create2.address, "release.create2.address");
  expect(/^0x[0-9a-f]+$/.test(r.bytecode.cborMetadata), "release.bytecode.cborMetadata: not lowercase hex");
  for (const ref of r.bytecode.immutableReferences) {
    expect(Number.isSafeInteger(ref.start) && ref.start >= 0 && ref.length === 32, "release: bad immutable reference");
  }
  return r;
}

export function renderRelease(text: string): string {
  const r = parseRelease(text);
  const refs = r.bytecode.immutableReferences.map((x) => `    { start: ${x.start}, length: ${x.length} },`).join("\n");
  return `${HEADER(SOURCES.release)}
/** Identity of the audited PayLinkV2 release artifact (protocol/deployments/README.md). */
export const RELEASE = {
  contract: "PayLinkV2",
  release: ${JSON.stringify(r.release)},
  initCodeHash: ${JSON.stringify(r.bytecode.initCodeHash)},
  initCodeSize: ${r.bytecode.initCodeSize},
  maskedRuntimeHash: ${JSON.stringify(r.bytecode.maskedRuntimeHash)},
  runtimeCodeSize: ${r.bytecode.runtimeCodeSize},
  /** Byte ranges of the seven OpenZeppelin EIP712 immutables in the runtime code, sorted by start. */
  immutableReferences: [
${refs}
  ],
  cborMetadata: ${JSON.stringify(r.bytecode.cborMetadata)},
  compiler: { solc: ${JSON.stringify(r.compiler.solc)}, evmVersion: ${JSON.stringify(r.compiler.evmVersion)}, settingsHash: ${JSON.stringify(r.compiler.settingsHash)} },
  openZeppelin: ${JSON.stringify(r.dependencies["@openzeppelin/contracts"])},
  create2: {
    factory: ${JSON.stringify(r.create2.factory)},
    salt: ${JSON.stringify(r.create2.salt)},
    saltPreimage: ${JSON.stringify(r.create2.saltPreimage)},
    address: ${JSON.stringify(r.create2.address)},
  },
} as const;
`;
}

// ----------------------------------------------------------------------------------- deployments

export interface DeploymentRecord {
  readonly chainId: number;
  readonly network: string;
  readonly address: `0x${string}`;
  readonly release: string;
  readonly method: "CREATE" | "CREATE2";
  readonly deployer: `0x${string}`;
  readonly txHash: `0x${string}`;
  readonly blockNumber: bigint;
  readonly initCodeHash: `0x${string}`;
  readonly maskedRuntimeHash: `0x${string}`;
  readonly runtimeCodeHash: `0x${string}`;
  readonly explorers: readonly { readonly name: string; readonly origin: string }[];
}

/**
 * Validates one `paylink.deployment/1` record against the release artifact. A record whose
 * init-code or masked runtime hash differs from `release.json` is not the audited contract and is refused.
 */
export function parseDeploymentRecord(text: string, fileChainId: number, release: ReleaseRecord): DeploymentRecord {
  const r = JSON.parse(text) as Record<string, unknown>;
  const where = `deployments/${fileChainId}.json`;
  expect(r["schema"] === "paylink.deployment/1", `${where}: schema must be paylink.deployment/1`);
  expect(r["contract"] === "PayLinkV2", `${where}: contract must be PayLinkV2`);
  expect(r["release"] === release.release, `${where}: release ${String(r["release"])} is not ${release.release}`);
  expect(r["chainId"] === fileChainId, `${where}: chainId does not match the file name`);
  expect(r["caip2"] === `eip155:${fileChainId}`, `${where}: caip2 mismatch`);
  const address = checksummed(r["address"], `${where} address`);
  expect(r["caip10"] === `eip155:${fileChainId}:${address}`, `${where}: caip10 mismatch`);
  expect(typeof r["network"] === "string" && r["network"] !== "", `${where}: network missing`);
  const d = r["deployment"] as Record<string, unknown>;
  expect(d["method"] === "CREATE" || d["method"] === "CREATE2", `${where}: deployment.method`);
  const deployer = checksummed(d["deployer"], `${where} deployment.deployer`);
  const txHash = hash32(d["txHash"], `${where} deployment.txHash`);
  expect(typeof d["blockNumber"] === "number" && Number.isSafeInteger(d["blockNumber"]) && d["blockNumber"] >= 0, `${where}: blockNumber`);
  if (d["method"] === "CREATE2") {
    expect(d["factory"] === release.create2.factory && d["salt"] === release.create2.salt, `${where}: CREATE2 parameters differ from the release`);
  } else {
    expect(d["factory"] === null && d["salt"] === null && d["saltPreimage"] === null, `${where}: CREATE records carry null CREATE2 fields`);
  }
  const b = r["bytecode"] as Record<string, unknown>;
  const initCodeHash = hash32(b["initCodeHash"], `${where} initCodeHash`);
  const maskedRuntimeHash = hash32(b["maskedRuntimeHash"], `${where} maskedRuntimeHash`);
  const runtimeCodeHash = hash32(b["runtimeCodeHash"], `${where} runtimeCodeHash`);
  expect(initCodeHash === release.bytecode.initCodeHash, `${where}: initCodeHash is not the release artifact's`);
  expect(maskedRuntimeHash === release.bytecode.maskedRuntimeHash, `${where}: maskedRuntimeHash is not the release artifact's`);
  const domain = r["eip712Domain"] as Record<string, unknown>;
  expect(
    domain["name"] === "PayLink" && domain["version"] === "2" && domain["chainId"] === fileChainId && domain["verifyingContract"] === address,
    `${where}: eip712Domain does not match {PayLink, 2, chainId, address}`,
  );
  const explorers = (r["explorers"] as readonly Record<string, unknown>[]).map((e) => {
    expect(typeof e["name"] === "string" && typeof e["address"] === "string", `${where}: explorer entry`);
    const link = new URL(e["address"]);
    expect(link.protocol === "https:" && link.pathname === `/address/${address}`, `${where}: explorer link ${e["address"]}`);
    return { name: e["name"], origin: link.origin };
  });
  return {
    chainId: fileChainId,
    network: r["network"],
    address,
    release: release.release,
    method: d["method"],
    deployer,
    txHash,
    blockNumber: BigInt(d["blockNumber"]),
    initCodeHash,
    maskedRuntimeHash,
    runtimeCodeHash,
    explorers,
  };
}

export function renderDeployments(records: readonly DeploymentRecord[]): string {
  const body = [...records]
    .sort((a, b) => a.chainId - b.chainId)
    .map(
      (d) => `  ${d.chainId}: {
    network: ${JSON.stringify(d.network)},
    address: ${JSON.stringify(d.address)},
    release: ${JSON.stringify(d.release)},
    method: ${JSON.stringify(d.method)},
    deployer: ${JSON.stringify(d.deployer)},
    txHash: ${JSON.stringify(d.txHash)},
    blockNumber: ${d.blockNumber}n,
    initCodeHash: ${JSON.stringify(d.initCodeHash)},
    maskedRuntimeHash: ${JSON.stringify(d.maskedRuntimeHash)},
    runtimeCodeHash: ${JSON.stringify(d.runtimeCodeHash)},
    explorers: [${d.explorers.map((e) => `{ name: ${JSON.stringify(e.name)}, origin: ${JSON.stringify(e.origin)} }`).join(", ")}],
  },`,
    )
    .join("\n");
  return `${HEADER(`${SOURCES.deploymentsDir}/<chainId>.json`)}
import type { Deployment } from "../types.ts";

/** A recorded deployment, before the registry applies its lifecycle status (src/deployment-status.ts). */
export interface DeploymentRecord extends Omit<Deployment, "status"> {
  /** Network name as written by the deploy script. */
  readonly network: string;
  /** Explorers the deploy script linked, by origin. */
  readonly explorers: readonly { readonly name: string; readonly origin: string }[];
}

/** Every recorded PayLinkV2 deployment, keyed by chain ID. Empty until the first testnet deployment is recorded. */
export const DEPLOYMENT_RECORDS: Readonly<Partial<Record<number, DeploymentRecord>>> = {${body === "" ? "" : `\n${body}\n`}};
`;
}

// ------------------------------------------------------------------------------------------ v1

export interface V1Config {
  readonly network: string;
  readonly chainId: number;
  readonly rpc: string;
  readonly explorer: string | null;
  readonly address: `0x${string}` | null;
}

/** Reads the JSON object literal that `web/config.js` assigns to `window.PAYLINK_CONFIG`. */
export function parseV1Config(text: string): V1Config {
  const match = /window\.PAYLINK_CONFIG\s*=\s*(\{[\s\S]*?\});/.exec(text);
  expect(match?.[1] !== undefined, "web/config.js: window.PAYLINK_CONFIG = {...}; not found");
  const c = JSON.parse(match[1]) as Record<string, unknown>;
  expect(typeof c["chainId"] === "number" && Number.isSafeInteger(c["chainId"]), "web/config.js: chainId");
  expect(typeof c["network"] === "string", "web/config.js: network");
  expect(typeof c["rpc"] === "string" && c["rpc"].startsWith("https://"), "web/config.js: rpc must be https");
  expect(c["explorer"] === null || (typeof c["explorer"] === "string" && c["explorer"].startsWith("https://")), "web/config.js: explorer");
  const address = c["address"] === null ? null : checksummed(c["address"], "web/config.js address");
  return { network: c["network"], chainId: c["chainId"], rpc: c["rpc"], explorer: c["explorer"], address };
}

export function renderV1(text: string): string {
  const c = parseV1Config(text);
  return `${HEADER(SOURCES.v1Config)}
/** The frozen v1 app's network configuration (Arc Microgrants entry, ADR 0010). \`address\` stays null until v1 is deployed. */
export const V1_CONFIG = {
  network: ${JSON.stringify(c.network)},
  chainId: ${c.chainId},
  rpc: ${JSON.stringify(c.rpc)},
  explorer: ${JSON.stringify(c.explorer)},
  address: ${JSON.stringify(c.address)},
} as const;
`;
}

// ---------------------------------------------------------------------------------------- driver

/** Renders every generated file from the repository at `repoDir`. Keys are paths relative to the package. */
export function renderAll(repoDir: string = REPO_DIR): ReadonlyMap<string, string> {
  const read = (relative: string): string => readFileSync(join(repoDir, relative), "utf8");
  const releaseText = read(SOURCES.release);
  const release = parseRelease(releaseText);
  const records = readdirSync(join(repoDir, SOURCES.deploymentsDir))
    .filter((name) => /^[1-9][0-9]*\.json$/.test(name))
    .map((name) => parseDeploymentRecord(read(`${SOURCES.deploymentsDir}/${name}`), Number(name.slice(0, -5)), release));
  return new Map([
    ["src/generated/gas.ts", renderGas(read(SOURCES.gasSnapshot), read(SOURCES.gasMeasurements), release.bytecode.initCodeHash)],
    ["src/generated/release.ts", renderRelease(releaseText)],
    ["src/generated/deployments.ts", renderDeployments(records)],
    ["src/generated/v1.ts", renderV1(read(SOURCES.v1Config))],
  ]);
}

// Command-line driver; the renderers above are unit-tested through test/generated.test.ts.
function main(argv: readonly string[]): number {
  const check = argv.includes("--check");
  let stale = 0;
  for (const [relative, content] of renderAll()) {
    const path = join(PACKAGE_DIR, relative);
    let current: string;
    try {
      current = readFileSync(path, "utf8");
    } catch {
      current = "";
    }
    if (current === content) {
      continue;
    }
    if (check) {
      stale += 1;
      console.error(`stale: ${relative} (run: node scripts/generate.ts)`);
    } else {
      writeFileSync(path, content);
      console.log(`wrote ${relative}`);
    }
  }
  return stale === 0 ? 0 : 1;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
