#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Known-answer vectors for the ledger backup file (ADR 0016), from an implementation independent of the app's.

HKDF-SHA-256 is written out here from RFC 5869 with the standard library (hmac, hashlib); AES-256-GCM comes from the
`cryptography` package. The app's WebCrypto code must reproduce these files byte for byte and open them
(apps/web/test/books.test.ts). Inputs are fixed test values, never real keys.

    python3 apps/web/test/vectors/books-vectors.py > apps/web/test/vectors/books-v1.json
"""
import hashlib
import hmac
import json
import sys

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

NAMESPACE = "paylink.books.v1"
PAD_BLOCK = 4096


def hkdf(ikm: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    okm, block, counter = b"", b"", 1
    while len(okm) < length:
        block = hmac.new(prk, block + info + bytes([counter]), hashlib.sha256).digest()
        okm += block
        counter += 1
    return okm[:length]


def b64url(data: bytes) -> str:
    import base64

    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def compact(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def seal(name: str, prf: bytes, merchant: str, chain_id: int, created_at: str, salt: bytes, iv: bytes, schema: int, content) -> dict:
    chain = f"eip155:{chain_id}"
    check = hkdf(prf, bytes(32), f"{NAMESPACE}/check".encode(), 32)
    key = hkdf(prf, salt, f"{NAMESPACE}/aes-256-gcm/{chain}/{merchant}".encode(), 32)
    header = {
        "format": "paylink.books",
        "version": 1,
        "schema": schema,
        "chain": chain,
        "merchant": merchant,
        "createdAt": created_at,
        "kdf": {"namespace": NAMESPACE, "hash": "SHA-256", "salt": b64url(salt), "check": b64url(check)},
        "cipher": {"name": "AES-256-GCM", "iv": b64url(iv)},
    }
    aad = compact(header)
    plaintext = compact(content).encode("utf-8")
    padded = plaintext.ljust(max(1, -(-len(plaintext) // PAD_BLOCK)) * PAD_BLOCK, b" ")
    sealed = AESGCM(key).encrypt(iv, padded, aad.encode("utf-8"))
    file = dict(header, ciphertext=b64url(sealed))
    return {
        "name": name,
        "input": {
            "prfOutput": prf.hex(),
            "merchant": merchant,
            "chainId": chain_id,
            "createdAt": created_at,
            "salt": salt.hex(),
            "iv": iv.hex(),
            "schema": schema,
            "content": content,
        },
        "expected": {
            "prfSalt": hashlib.sha256(NAMESPACE.encode()).hexdigest(),
            "check": b64url(check),
            "key": key.hex(),
            "aad": aad,
            "plaintextBytes": len(plaintext),
            "paddedBytes": len(padded),
            "file": json.dumps(file, ensure_ascii=False, indent=2) + "\n",
        },
    }


def main() -> None:
    # anvil's public test accounts 0 and 1: test addresses only.
    merchant = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    contact = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    prf = bytes(range(32))
    vectors = [
        seal(
            "schema 2: an address-book entry with a non-ASCII label",
            prf,
            merchant,
            10143,
            "2026-10-09T01:00:00.000Z",
            bytes(range(32, 64)),
            bytes(range(64, 76)),
            2,
            {"invoices": [], "receipts": [], "contacts": [{"address": contact, "label": "Rasoa — épicerie", "card": None, "updatedAt": 1791417600000}]},
        ),
        seal(
            "schema 1: invoices and receipts only (upgraded on restore)",
            bytes(range(1, 33)),
            merchant,
            10143,
            "2026-10-09T01:00:00.000Z",
            bytes(range(100, 132)),
            bytes(range(200, 212)),
            1,
            {"invoices": [], "receipts": []},
        ),
    ]
    out = {
        "$comment": "Generated by books-vectors.py (independent HKDF from RFC 5869 + pyca/cryptography AES-GCM). Do not edit by hand.",
        "namespace": NAMESPACE,
        "vectors": vectors,
    }
    sys.stdout.write(json.dumps(out, ensure_ascii=False, indent=2) + "\n")


if __name__ == "__main__":
    main()
