// SPDX-License-Identifier: MIT
/**
 * The Worker as Cloudflare runs it: the bundle built by scripts/build.ts, served by `wrangler dev` (workerd, the
 * Workers runtime) with deploy/wrangler.toml as is, so the Durable Object binding, its SQLite migration, the
 * compatibility date, `no_bundle` and the secret all take the production path. Only the registry module differs:
 * it points at anvil (`buildWorker({ registryModule })`, the seam in src/worker/registry.ts).
 *
 * What this proves beyond the Node adapter: the bundle loads in workerd (no Node built-in, no forbidden global-scope
 * operation), the stateless front reaches the ChainSender over Durable Object RPC, state lives in Durable Object
 * storage, the tracker runs from Durable Object alarms, and `RELAYER_PK` arrives as a secret binding.
 */
import { spawn } from "node:child_process";
import type { ChildProcess } from "node:child_process";
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { authorizePayment, decodeInvoiceFragment, expiresIn, issueInvoice, readLinkState, signCancel, toCancelAuthorizationJson } from "@paylink/sdk";
import type { DecodedInvoiceLink, RelayPayRequestJson } from "@paylink/sdk";
import type { Hex } from "viem";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { buildWorker, DEPLOY_DIR } from "../../scripts/build.ts";
import type { LocalChain } from "../fixtures/chain.ts";
import { CHAIN_ID, chainAvailable, freePort, KEYS, startChain } from "../fixtures/chain.ts";
import { call, post } from "../fixtures/http.ts";

const PACKAGE_DIR = new URL("../../", import.meta.url).pathname;
const APP = "https://paylink-mg.pages.dev";

/** TypeScript source of the test registry: the anvil chain, as a local chain the test bundle may relay. */
function registrySource(chain: LocalChain): string {
  const deployment = chain.local.deployment;
  const token = chain.local.tokens[0];
  if (deployment === null || token === undefined) {
    throw new Error("the local chain needs a deployment and a token");
  }
  return `// GENERATED by test/integration/worker.test.ts: a test registry, never deployed.
import { createRegistry, defineLocalChain, MONAD_GAS_TABLE, monadTestnet } from "@paylink/chains";
const local = defineLocalChain({
  chainId: ${String(CHAIN_ID)},
  rpcUrl: ${JSON.stringify(chain.url)},
  chargesGasLimit: true,
  gas: MONAD_GAS_TABLE,
  tokens: [${JSON.stringify(token)}],
  deployment: { address: ${JSON.stringify(deployment.address)}, status: "active", release: "2.0.0", method: "CREATE", deployer: ${JSON.stringify(deployment.deployer)}, txHash: ${JSON.stringify(deployment.txHash)}, blockNumber: 1n, initCodeHash: ${JSON.stringify(deployment.initCodeHash)}, maskedRuntimeHash: ${JSON.stringify(deployment.maskedRuntimeHash)}, runtimeCodeHash: ${JSON.stringify(deployment.runtimeCodeHash)} },
});
const faucetGas = monadTestnet.contracts.ausdFaucet?.gas;
if (faucetGas === undefined) throw new Error("faucet gas bounds");
export const source = createRegistry([{ ...local, contracts: { ausdFaucet: { address: ${JSON.stringify(chain.faucet)}, confidence: "C", gas: faucetGas } } }]);
export const allowLocal = true;
`;
}

async function waitFor<T>(probe: () => Promise<T | undefined>, timeoutMs: number): Promise<T> {
  const until = Date.now() + timeoutMs;
  for (;;) {
    const value = await probe().catch((error: unknown) => {
      if (process.env["RELAYER_TEST_DEBUG"] !== undefined) {
        process.stderr.write(`waitFor: ${String(error)} ${String((error as { cause?: unknown }).cause)}\n`);
      }
      return undefined;
    });
    if (value !== undefined) {
      return value;
    }
    if (Date.now() > until) {
      throw new Error("timed out");
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
}

describe.skipIf(!chainAvailable())("the Worker bundle in workerd (wrangler dev) against anvil", () => {
  let chain: LocalChain;
  let dev: ChildProcess | undefined;
  let base = "";
  let output = "";
  const dir = join(PACKAGE_DIR, ".test-cache", `worker-${String(process.pid)}`);

  const invoice = async (amount: bigint, maxPayments: number): Promise<DecodedInvoiceLink> => {
    const t = await chain.now();
    const issued = await issueInvoice({
      registry: chain.registry,
      chainId: CHAIN_ID,
      draft: { payee: chain.accounts.payee.address, token: chain.token, amount, maxPayments, validAfter: t - 60n, expiry: expiresIn(t) },
      signer: chain.accounts.payee,
      client: chain.client,
    });
    return decodeInvoiceFragment(issued.fragment, chain.registry);
  };

  beforeAll(async () => {
    chain = await startChain();
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "registry.ts"), registrySource(chain));
    const files = await buildWorker({ registryModule: join(dir, "registry.ts") });
    writeFileSync(join(dir, "worker.js"), files["worker.js"]);
    copyFileSync(join(DEPLOY_DIR, "wrangler.toml"), join(dir, "wrangler.toml"));
    // The local stand-in for the dashboard secret (anvil's public test account 3).
    writeFileSync(join(dir, ".dev.vars"), `RELAYER_PK=${KEYS.relayer}\n`);
    const port = await freePort();
    dev = spawn(join(PACKAGE_DIR, "node_modules/.bin/wrangler"), ["dev", "--local", "--ip", "127.0.0.1", "--port", String(port), "--show-interactive-dev-session=false", "--log-level", process.env["RELAYER_TEST_DEBUG"] === undefined ? "warn" : "debug"], {
      cwd: dir,
      detached: true,
      // Not vitest's environment: wrangler behaves differently when it sees VITEST or a test NODE_ENV.
      env: { ...Object.fromEntries(Object.entries(process.env).filter(([name]) => !/^(VITEST|NODE_OPTIONS$|NODE_ENV$|TEST$)/u.test(name))), WRANGLER_SEND_METRICS: "false", NO_COLOR: "1", CI: "1" },
      stdio: ["ignore", "pipe", "pipe"],
    });
    dev.stdout?.on("data", (chunk: Buffer) => {
      output += chunk.toString();
      if (process.env["RELAYER_TEST_DEBUG"] !== undefined) {
        process.stderr.write(chunk);
      }
    });
    dev.stderr?.on("data", (chunk: Buffer) => {
      output += chunk.toString();
      if (process.env["RELAYER_TEST_DEBUG"] !== undefined) {
        process.stderr.write(chunk);
      }
    });
    base = `http://127.0.0.1:${String(port)}`;
    await waitFor(async () => ((await fetch(`${base}/v1/health`, { signal: AbortSignal.timeout(5_000) })).status > 0 ? true : undefined), 60_000).catch((error: unknown) => {
      throw new Error(`wrangler dev did not start: ${String(error)}\n${output}`);
    });
  }, 120_000);

  afterAll(() => {
    if (dev?.pid !== undefined) {
      try {
        process.kill(-dev.pid, "SIGTERM");
      } catch {
        // already gone
      }
    }
    chain.stop();
    rmSync(dir, { recursive: true, force: true });
  });

  it("serves health from the chain's Durable Object, with the relayer derived from the secret", async () => {
    const health = await waitFor(async () => {
      const reply = await call(base, "/v1/health");
      return reply.status === 200 ? reply : undefined;
    }, 30_000);
    expect(health.body).toMatchObject({ status: "ok", service: "paylink-relayer", chains: [{ chainId: CHAIN_ID, state: "ready", relayer: chain.accounts.relayer.address, deployment: chain.payLink }] });
    expect(health.headers.get("x-request-id")).toMatch(/^[0-9a-f-]{36}$/u);
  });

  it("applies the CORS policy in workerd", async () => {
    const preflight = await fetch(`${base}/v1/${String(CHAIN_ID)}/pay`, { method: "OPTIONS", headers: { origin: APP, "access-control-request-method": "POST" } });
    expect(preflight.status).toBe(204);
    expect(preflight.headers.get("access-control-allow-origin")).toBe(APP);
    const refused = await post(base, `/v1/${String(CHAIN_ID)}/onboard`, { chainId: CHAIN_ID, address: chain.accounts.payer.address }, { origin: "https://paylink-mg.pages.dev.evil.example" });
    expect(refused.status).toBe(403);
  });

  it("relays a payment, tracks it to its receipt from an alarm, and answers the replay with the settled transaction", async () => {
    const link = await invoice(7_000_000n, 1);
    const authorized = await authorizePayment({ outstanding: null, link, signer: chain.accounts.payer, now: await chain.now(), client: chain.client });
    const body = JSON.parse(JSON.stringify(authorized.request)) as RelayPayRequestJson;
    const reply = await post(base, `/v1/${String(CHAIN_ID)}/pay`, body, { origin: APP });
    expect(reply.status, JSON.stringify(reply.body) + output).toBe(202);
    const receipt = await chain.client.waitForTransactionReceipt({ hash: reply.body["txHash"] as Hex });
    expect(receipt.status).toBe("success");
    expect((await chain.client.getTransaction({ hash: receipt.transactionHash })).value).toBe(0n);
    // Only the alarm-driven tracker records the settlement; the replay then gets the settled transaction.
    const replay = await waitFor(async () => {
      const again = await post(base, `/v1/${String(CHAIN_ID)}/pay`, body);
      return again.status === 200 && again.body["status"] === "settled" ? again : undefined;
    }, 20_000);
    expect(replay.body).toMatchObject({ duplicate: true, txHash: reply.body["txHash"] });
  });

  it("rejects a tampered amount without sending anything", async () => {
    const link = await invoice(8_000_000n, 1);
    const body = JSON.parse(JSON.stringify((await authorizePayment({ outstanding: null, link, signer: chain.accounts.payer2, now: await chain.now(), client: chain.client })).request)) as RelayPayRequestJson;
    const before = await chain.client.getTransactionCount({ address: chain.accounts.relayer.address });
    const reply = await post(base, `/v1/${String(CHAIN_ID)}/pay`, { ...body, authorization: { ...body.authorization, amount: "8000001" } });
    expect(reply).toMatchObject({ status: 422, body: { code: "rejected", rule: "WrongAmount" } });
    expect(await chain.client.getTransactionCount({ address: chain.accounts.relayer.address })).toBe(before);
  });

  it("relays a signed cancellation and onboards from the faucet", async () => {
    const link = await invoice(1_000_000n, 2);
    const cancel = await signCancel({ signer: chain.accounts.payee, deployment: { chainId: CHAIN_ID, verifyingContract: chain.payLink }, invoice: link.invoice, deadline: (await chain.now()) + 3_600n });
    const cancelled = await post(base, `/v1/${String(CHAIN_ID)}/cancel`, toCancelAuthorizationJson(cancel));
    expect(cancelled.status).toBe(202);
    await chain.client.waitForTransactionReceipt({ hash: cancelled.body["txHash"] as Hex });
    expect((await readLinkState(chain.client, chain.payLink, link.key)).cancelled).toBe(true);

    const funded = await post(base, `/v1/${String(CHAIN_ID)}/onboard`, { chainId: CHAIN_ID, address: "0x000000000000000000000000000000000000bEEF" });
    expect(funded.status).toBe(202);
    await chain.client.waitForTransactionReceipt({ hash: funded.body["txHash"] as Hex });
    expect(await chain.balanceOf("0x000000000000000000000000000000000000bEEF")).toBe(10_000_000_000n);
    const cooling = await post(base, `/v1/${String(CHAIN_ID)}/onboard`, { chainId: CHAIN_ID, address: "0x000000000000000000000000000000000000cafE" });
    expect(cooling).toMatchObject({ status: 503, body: { code: "faucet-unavailable" } });
  });

  it("logs JSON lines from workerd without the key", () => {
    expect(output).not.toContain(KEYS.relayer.slice(2));
  });
});
